// content.js — 발표 스크립트 기반 31개 씬 (원천 데이터)
// 화면에는 짧은 카피만, 긴 설명은 speakerNote로 보존한다.

export const DECK = {
  title: 'AI Native Campus',
  subtitle: '전환을 위한 대학의 AI 교육 인프라',
  brand: 'Tilon',
};

export const SECTIONS = [
  { id: 'opening',   name: 'Opening',                     color: '#00e5ff' },
  { id: 'context',   name: 'Context',                     color: '#4f7cff' },
  { id: 'pain',      name: 'Pain Point',                  color: '#ff5c7a' },
  { id: 'framework', name: 'Framework',                   color: '#7c5cff' },
  { id: 'coretech',  name: 'Core Technologies',           color: '#00e5ff' },
  { id: 'scenarios', name: 'Integrated Learning Scenarios', color: '#37d0a0' },
  { id: 'platform',  name: 'All-in-One Education Platform', color: '#f4b53f' },
  { id: 'cases',     name: 'University Cases',            color: '#4f7cff' },
  { id: 'impact',    name: 'Impact & Closing',            color: '#00e5ff' },
];

export const SCENES = [
  // ───────────────────────── 1. OPENING ─────────────────────────
  {
    id: 'opening',
    section: 'opening',
    title: 'AI Native Campus',
    headline: 'AI Native Campus 전환을 위한\n대학의 AI 교육 인프라',
    body: 'AI를 도입하는 대학에서, AI로 태어나는 대학으로',
    type: 'hero',
    transition: 'zoom',
    effects: ['webgl-network', 'particles', 'mouse-parallax', 'kinetic-typography'],
    keywords: ['AI Native Campus'],
    speakerNote: '안녕하십니까. 오늘 AI Native Campus 전환을 위한 대학의 AI 교육 인프라에 대해서 말씀드리겠습니다.',
  },

  // ───────────────────────── 2. CONTEXT ─────────────────────────
  {
    id: 'ai-is-here',
    section: 'context',
    title: 'AI Is Already Here',
    headline: '지난 일주일,\nAI를 한 번도 쓰지 않은 사람이 있을까요?',
    body: 'AI는 이미 일상과 업무의 기본 도구가 되었다',
    type: 'question-orbit',
    transition: 'fade',
    effects: ['svg-path', 'orbit-icons', 'morph-timeline'],
    keywords: ['업무', '학습', '행정', '연구'],
    data: {
      orbit: [
        { icon: 'work', label: '업무' },
        { icon: 'study', label: '학습' },
        { icon: 'admin', label: '행정' },
        { icon: 'research', label: '연구' },
      ],
      timeline: [
        { era: '과거', label: 'AI 활용 금지', tone: 'ban' },
        { era: '현재', label: 'AI 활용 장려', tone: 'go' },
      ],
    },
    speakerNote: '오늘 여기 오신 분들 중 지난 일주일 동안 AI를 단 한 번도 업무에 사용하지 않으신 분은 없을 것입니다. 그만큼 AI는 일상과 업무에 가까이 다가왔습니다. 과거에는 대학에서 AI 활용을 부정행위로 보기도 했지만, 최근에는 AI 중심대학, AID 전환사업 등으로 대학 내 AI 활용이 정책적으로 장려되고 있습니다.',
  },

  // ───────────────────────── 3. PAIN POINT ─────────────────────────
  {
    id: 'voices',
    section: 'pain',
    title: 'Voices From Campus',
    headline: 'Infrastructure Gap',
    body: 'AI 교육은 확대되지만, 현장의 인프라는 아직 따라가지 못하고 있다',
    type: 'voices',
    transition: 'push',
    effects: ['speech-reveal', 'text-scramble', 'pulse'],
    keywords: ['학생', '교수', 'IT 운영자'],
    data: {
      voices: [
        { who: '학생', icon: 'student', quote: '노트북에서 안 돌아가요' },
        { who: '교수', icon: 'professor', quote: 'GPU가 부족해요' },
        { who: 'IT 운영자', icon: 'operator', quote: '데이터 통제가 안 돼요' },
      ],
    },
    speakerNote: '정책의 방향과는 별개로 대학 교육 현장에서는 여러 목소리가 들려옵니다. 노트북에서 안 돌아간다, GPU가 부족하다, 데이터 통제가 어렵다. 학생도 교수님도 IT 운영자도 각자의 자리에서 답답함을 호소합니다. AI 교육은 확대되고 있지만 이를 안정적으로 뒷받침할 AI 인프라는 아직 부족합니다.',
  },
  {
    id: 'definition',
    section: 'pain',
    title: 'AI Native Campus란',
    headline: 'AI를 모든 전공의\n기본 도구로 내재화한다',
    body: '하나의 인프라가 모든 전공의 AI 학습·연구를 동시에 지원한다',
    type: 'node-map',
    transition: 'fade',
    effects: ['node-network', 'svg-path', 'glow', 'mouse-parallax'],
    keywords: ['모든 전공', '하나의 인프라'],
    data: {
      core: 'AI Infrastructure',
      nodes: ['인문', '경영', '공학', '디자인', '의학', '행정'],
    },
    speakerNote: 'AI Native Campus의 핵심은 AI를 특정 학과나 일부 전문가만의 기술로 두는 것이 아니라, 모든 전공의 기본 도구로 내재화하는 것입니다. 전공마다 별도 환경을 따로 구축하는 것이 아니라 하나의 인프라 안에서 다양한 AI 학습과 연구 니즈를 동시에 지원하는 것이 중요합니다.',
  },
  {
    id: 'pain-points',
    section: 'pain',
    title: 'University Pain Points',
    headline: '대학이 안고 있는\n복합적인 Pain Point',
    body: 'AI 교육과 행정의 디지털 전환 과정에서 문제는 서로 얽혀 있다',
    type: 'pain-cards',
    transition: 'push',
    effects: ['morph-converge', 'magnetic-card', 'scroll-reveal'],
    keywords: ['인프라 분산', '실습환경 부족', '원격교육 한계', '보안 리스크'],
    data: {
      cards: [
        { icon: 'scatter', title: 'AI 교육 인프라 분산', desc: '학과별·건물별로 흩어진 실습 자원' },
        { icon: 'gpu', title: 'AI 실습환경 부족', desc: '고사양 장비 없이는 수업이 어려움' },
        { icon: 'remote', title: '원격교육 한계', desc: '실습실 밖에서는 같은 환경 재현 불가' },
        { icon: 'shield', title: '데이터 보안 리스크', desc: '외부 AI 사용 시 데이터 유출 우려' },
      ],
    },
    speakerNote: '현재 대부분의 대학은 AI 교육 인프라 분산, AI 실습환경 부족, 원격교육 한계, 데이터 보안 리스크 등 AI 교육과 행정의 디지털 전환 과정에서 복합적인 Pain Point를 안고 있습니다.',
  },

  // ───────────────────────── 4. FRAMEWORK ─────────────────────────
  {
    id: 'framework',
    section: 'framework',
    title: '대학 AI 인프라 표준 프레임워크',
    headline: '3가지 활용 모델,\n하나의 인프라',
    body: '틸론이 제시하는 대학 AI 인프라 표준 프레임워크',
    type: 'framework',
    transition: 'wipe',
    effects: ['layer-stack', 'block-assembly', 'svg-connectors', 'step-reveal'],
    keywords: ['Build AI', 'Build with AI', 'Use AI', '5대 핵심 기술'],
    data: {
      models: [
        { key: 'build', title: 'AI를 만드는 사람', sub: 'AI 모델 개발' },
        { key: 'buildwith', title: 'AI로 만드는 사람', sub: 'AI 기반 SW 개발' },
        { key: 'use', title: 'AI를 쓰는 사람', sub: '모든 전공의 AI 활용' },
      ],
      blocks: ['Virtual Desktop', 'GPU Slicing', 'Sovereign AI', 'AI Dev Platform', 'Education Platform'],
    },
    speakerNote: '틸론은 대학 AI 인프라 표준 프레임워크를 제시합니다. 대학에서 AI를 활용하는 방법은 다양하지만 크게 세 가지로 구분할 수 있습니다. AI 모델을 직접 개발하는 학생과 교수, AI 기반 SW 개발 실습을 하는 공과계열 학생, 다양한 전공에서 AI 활용 역량을 키우는 학생입니다. 각각 필요 도구와 자원은 다르지만 하나의 인프라에서 지원할 수 있습니다. 이를 가능하게 하는 것이 5가지 핵심 기술입니다.',
  },
  {
    id: 'user-types',
    section: 'framework',
    title: 'Three AI User Types',
    headline: '요구는 다르지만,\n인프라는 하나면 된다',
    body: 'Use AI · Build AI · Build with AI',
    type: 'user-types',
    transition: 'push',
    effects: ['magnetic-card', 'morph-connection', 'mouse-parallax'],
    keywords: ['Use AI', 'Build AI', 'Build with AI'],
    data: {
      types: [
        { key: 'use', en: 'Use AI', ko: 'AI를 쓰는 사람', needs: ['Internal AI', 'External LLM', '가상 데스크톱'] },
        { key: 'build', en: 'Build AI', ko: 'AI를 만드는 사람', needs: ['GPU 자원', 'Jupyter · PyTorch', '데이터셋 스토리지'] },
        { key: 'buildwith', en: 'Build with AI', ko: 'AI로 만드는 사람', needs: ['Copilot 등 AI 도구', 'CI/CD 파이프라인', '컨테이너 환경'] },
      ],
    },
    speakerNote: 'AI를 쓰는 사람, AI를 만드는 사람, AI로 만드는 사람은 서로 요구하는 도구와 자원이 다르지만 하나의 인프라로 모두 만족시킬 수 있습니다.',
  },

  // ───────────────────────── 5. CORE TECHNOLOGIES ─────────────────────────
  {
    id: 'five-core',
    section: 'coretech',
    title: '5대 핵심 기술',
    headline: 'AI 통합 인프라를 완성하는\n5가지 핵심 기술',
    body: '',
    type: 'tech-rings',
    transition: 'zoom',
    effects: ['particle-orbit', 'ring-drawing', 'sequential-light'],
    keywords: ['Virtual Desktop', 'GPU Slicing', 'Sovereign AI', 'Tstation', 'CAS · CBT'],
    data: {
      rings: [
        { n: 1, title: 'Virtual Desktop', sub: '시공간 제약 없는 실습환경' },
        { n: 2, title: 'GPU Slicing', sub: '활용률 극대화' },
        { n: 3, title: 'Sovereign AI', sub: 'iStation' },
        { n: 4, title: 'AI Dev Platform', sub: 'Tstation' },
        { n: 5, title: 'Education Platform', sub: 'CAS · CBT' },
      ],
    },
    speakerNote: '지금부터 AI 통합 인프라에 적용된 5가지 핵심 기술을 설명드리겠습니다.',
  },
  {
    id: 'virtual-desktop',
    section: 'coretech',
    title: 'Core Tech 01 · Virtual Desktop',
    headline: '시간과 공간의 제약 없이,\n똑같은 AI 실습환경',
    body: 'OS · SW · 데이터 · 프로파일까지 전부 클라우드에서',
    type: 'tech-vdi',
    transition: 'wipe',
    effects: ['device-parallax', 'cloud-flow', 'equality-morph'],
    keywords: ['Anyone', 'Anytime', 'Anywhere'],
    data: {
      cloud: ['OS', 'SW', '사용자 데이터', '프로파일'],
      devices: ['노트북', 'PC', '태블릿', '스마트폰', '제로클라이언트'],
      compare: { left: '300만원 최신 노트북', right: '10년 된 노트북', eq: '똑같은 AI 실습' },
    },
    speakerNote: '첫 번째 핵심기술은 시간과 공간 제약 없이 학습 가능한 가상 데스크톱 기술입니다. OS와 소프트웨어, 사용자 데이터와 사용자 프로파일까지 모두 클라우드에서 운영하여 언제 어디서나 어떤 단말기로든 본인의 가상 PC에 접속할 수 있습니다. 300만원짜리 최신 노트북을 가진 학생이나 10년 된 노트북을 가진 학생이나 똑같은 AI 실습이 가능합니다.',
  },
  {
    id: 'gpu-slicing',
    section: 'coretech',
    title: 'Core Tech 02 · GPU Slicing',
    headline: 'GPU 활용률\n10~15% → 최대 90%',
    body: '고가 GPU 자원을 다수 사용자에게 실시간 동적 할당·회수',
    type: 'gpu-compare',
    transition: 'fade',
    effects: ['data-counter', 'particle-split', 'morph-chart'],
    keywords: ['90%', '30명 이상', '동적 할당'],
    data: {
      before: { label: '기존 GPU 활용률', value: 15, prefix: '10~', suffix: '%' },
      after: { label: 'GPU Slicing 적용', value: 90, suffix: '%' },
      vs: [
        { name: 'NVIDIA MIG', points: ['하드웨어 기반 고정 분할', '최대 7개 분할', '재구성 필요'] },
        { name: 'Tilon GPU Slicing', points: ['소프트웨어 기반 가상화', '30명 이상 동시 할당', '실시간 동적 할당·회수'], hot: true },
      ],
    },
    speakerNote: '두 번째 핵심기술은 GPU Slicing입니다. 고가의 GPU 자원은 평균적으로 10~15%만 활용되는 경우가 많습니다. 틸론의 GPU Slicing 기술은 GPU 자원 활용률을 90%까지 높여줍니다. 워크스테이션급 장비 없이도 AI 학습, 3D 모델링, 의료영상 분석 등의 작업이 가능해집니다. NVIDIA MIG가 하나의 GPU를 최대 7개까지 나누는 하드웨어 기반 기술이라면, 틸론 GPU Slicing은 다수 사용자에게 GPU 자원을 30명 이상 실시간 동적으로 할당하고 회수할 수 있는 소프트웨어 기반 GPU 가상화 기술입니다.',
  },
  {
    id: 'sovereign-ai',
    section: 'coretech',
    title: 'Core Tech 03 · Sovereign AI',
    headline: '내부 데이터는 밖으로,\n한 발짝도 나가지 않는다',
    body: 'iStation = Internal AI + AI Router + Tokenizer',
    type: 'sovereign',
    transition: 'wipe',
    effects: ['shield-layer', 'secure-flow', 'day-night-timeline'],
    keywords: ['Internal AI', 'AI Router', 'Tokenizer'],
    data: {
      modules: [
        { name: 'Internal AI', desc: '교내 데이터 학습·답변' },
        { name: 'AI Router', desc: '작업 유형별 GPU 자동 배정' },
        { name: 'Tokenizer', desc: '외부 LLM 통합 관리' },
      ],
      dayNight: { day: '수업 · 실습 중심', night: 'AI 모델 학습 중심' },
    },
    speakerNote: '세 번째 핵심 기술은 Sovereign AI입니다. 틸론의 iStation은 Internal AI, AI Router, Tokenizer를 통합한 솔루션입니다. iStation은 대학 내부 데이터의 외부 유출을 차단하면서 안전한 Internal AI 활용 환경을 제공합니다. 사용자의 작업 유형과 GPU 사용 수요를 분석해 교내 GPU 자원을 자동 배정하고, 주간에는 수업과 실습 중심으로, 야간에는 AI 모델 학습 중심으로 전환 운영하여 GPU 활용률을 극대화합니다.',
  },
  {
    id: 'jeju-sovereign',
    section: 'coretech',
    title: '제주대학교 Sovereign AI',
    headline: '국립대 최초,\nSovereign AI 구축',
    body: '제주대학교 × iStation',
    type: 'case-feature',
    transition: 'push',
    effects: ['case-reveal', 'doc-flow', 'citation-highlight'],
    keywords: ['권한 기반 접근 제어', '아래한글 학습', '출처 기반 답변'],
    data: {
      badge: '제주대학교',
      features: [
        { title: '권한 기반 접근 제어', desc: '역할별 맞춤 답변 제공' },
        { title: '아래한글 문서 학습', desc: '공공 행정 문서 특화 학습환경' },
        { title: '출처 기반 답변 + 추천 질문', desc: '할루시네이션 없는 검증 가능한 AI' },
      ],
    },
    speakerNote: '제주대학교는 틸론의 iStation으로 국립대 최초 Sovereign AI를 구축한 바 있습니다. 학습된 데이터의 권한 기반 접근 제어로 역할별 맞춤 답변을 제공하고, 아래한글 문서 학습을 지원하여 공공 행정 문서에 특화된 학습환경을 지원합니다. 답변에는 출처가 함께 제시되고 관련 추천 질문까지 자동 제공됩니다. 할루시네이션 없는 출처 검증이 가능한 신뢰 가능한 AI 학사 도구입니다.',
  },
  {
    id: 'tokenizer',
    section: 'coretech',
    title: 'External LLM Tokenizer',
    headline: '외부 LLM도 통합 관리,\n비용은 정확히 배분',
    body: 'Claude · GPT · Gemini 를 하나의 창구로',
    type: 'tokenizer',
    transition: 'fade',
    effects: ['token-counter', 'model-switch', 'dashboard-reveal'],
    keywords: ['토큰 사용량', '비용 배분', '사용 패턴 분석'],
    data: {
      models: ['Claude', 'GPT', 'Gemini'],
      flows: ['부서별', '학과별', '사용자별'],
      insight: 'AI 사용 패턴 분석 → 차기 인프라 투자 의사결정',
    },
    speakerNote: 'iStation은 외부의 다양한 유료 LLM을 Tokenizer 형태로 제공합니다. Claude, GPT, Gemini 등 다양한 모델을 선택할 수 있고 토큰 사용량이 실시간으로 표시됩니다. 부서, 학과, 사용자별로 정확한 비용 배분이 가능하며, 대시보드에서 AI 사용 패턴을 분석해 차기 인프라 투자 의사결정까지 지원합니다.',
  },
  {
    id: 'tstation',
    section: 'coretech',
    title: 'Core Tech 04 · Tstation',
    headline: '실습환경 설정 몇 시간을,\n접속 즉시 1분으로',
    body: 'IaC(Infra as Code) 기반 표준 AI 개발환경',
    type: 'tstation',
    transition: 'wipe',
    effects: ['chaos-to-order', 'iac-stack', 'pipeline-draw'],
    keywords: ['IaC', 'Jupyter', 'VSCode', 'GPU + Memory'],
    data: {
      chaos: ['버전 충돌', 'CUDA 오류', '패키지 지옥', '환경 편차'],
      order: ['Jupyter', 'VSCode', 'GPU', 'Memory', 'Dataset', 'Source Code'],
    },
    speakerNote: '네 번째 핵심 기술은 AI 개발환경 통합 플랫폼입니다. AI 수업에서 가장 큰 어려움 중 하나는 실습환경 설정입니다. Tstation은 이러한 환경을 IaC, Infra as Code 기반으로 제공합니다. 학생은 접속 즉시 개발을 시작할 수 있고 교수는 수업별 표준 실습환경을 손쉽게 생성할 수 있습니다. 데이터와 소스코드는 중앙 서버에 저장되어 보안성이 강화되고 GPU와 메모리를 함께 할당하여 코딩뿐 아니라 실행까지 가능합니다.',
  },
  {
    id: 'tstation-demo',
    section: 'coretech',
    title: 'Tstation Demo',
    headline: 'Jupyter · VSCode · 공동작업,\n접속 즉시 시작',
    body: '컨테이너 · Kubernetes · GPU 실시간 할당 관리',
    type: 'demo-video',
    transition: 'fade',
    effects: ['video-frame', 'terminal-typing', 'resource-motion'],
    keywords: ['Jupyter', 'VSCode', 'Kubernetes', 'GPU'],
    data: {
      videos: [
        { src: 'tstation-demo-1', label: 'Tstation 개발환경 접속' },
        { src: 'tstation-demo-2', label: '자원 할당 · 관리 콘솔' },
      ],
    },
    speakerNote: 'Tstation 데모 화면입니다. 학생은 Jupyter, VSCode 등 본인의 AI 개발 환경에 바로 접속할 수 있습니다. 다른 인원과 공동작업은 물론 GPU 자원 할당으로 실행까지 바로 확인할 수 있습니다. 별도의 관리툴에서 컨테이너, Kubernetes와 GPU 자원을 실시간 할당하고 관리할 수 있습니다.',
  },

  // ───────────────────────── 6. SCENARIOS ─────────────────────────
  {
    id: 'scenario-ai-major',
    section: 'scenarios',
    title: 'AI 전공 학생',
    headline: '모델 학습부터 실행, 접속까지\n하나의 흐름으로',
    body: 'AI 전공 학생의 학습 파이프라인',
    type: 'workflow',
    transition: 'push',
    effects: ['horizontal-flow', 'svg-path', 'step-reveal'],
    keywords: ['PyTorch', 'Jupyter', 'VDI', 'GPU'],
    data: {
      steps: [
        { name: 'PyTorch', desc: '모델 학습' },
        { name: 'Jupyter', desc: '실행 · 실험' },
        { name: 'VDI', desc: '어디서든 접속' },
        { name: 'GPU', desc: '자원 자동 할당' },
      ],
      persona: 'AI 전공 학생',
    },
    speakerNote: 'AI 인프라 표준 프레임워크를 통해 인공지능 전공 학생은 PyTorch로 모델을 학습하고, Jupyter에서 실행하고, VDI로 어디서든 접속합니다.',
  },
  {
    id: 'scenario-cs',
    section: 'scenarios',
    title: '컴퓨터공학 학생',
    headline: 'AI 도구와 DevOps 환경을\n통합 활용한다',
    body: '코드 작성 → 빌드 → 배포 → 실행',
    type: 'workflow',
    transition: 'push',
    effects: ['cicd-pipeline', 'code-typing', 'container-motion'],
    keywords: ['Copilot', 'Jenkins', 'Docker', 'Kubernetes'],
    data: {
      steps: [
        { name: 'Copilot', desc: 'AI 코딩' },
        { name: 'Jenkins', desc: '빌드 자동화' },
        { name: 'Docker', desc: '컨테이너화' },
        { name: 'Kubernetes', desc: '배포 · 실행' },
      ],
      persona: '컴퓨터공학 학생',
    },
    speakerNote: '컴퓨터공학 학생은 Copilot 등 AI 도구로 코딩하고 Jenkins, Docker, Kubernetes로 CI/CD를 자동화합니다.',
  },
  {
    id: 'scenario-ax',
    section: 'scenarios',
    title: 'AX 실습',
    headline: '모든 전공이 AI로\n실무 역량을 기른다',
    body: 'Internal AI + External Tokenizer로 교과 학습과 업무 자동화',
    type: 'split-flow',
    transition: 'push',
    effects: ['split-ai-flow', 'prompt-output', 'usecase-cards'],
    keywords: ['과제', '보고서', '데이터 분석', '업무 자동화'],
    data: {
      left: { name: 'Internal AI', desc: '교내 데이터 기반' },
      right: { name: 'External Tokenizer', desc: 'Claude · GPT · Gemini' },
      center: ['과제 · 보고서', '데이터 분석', '비즈니스 자동화'],
      persona: '다양한 전공 학생',
    },
    speakerNote: 'AX 실습 환경에서는 Internal AI와 외부 AI Tokenizer를 통해 교과 학습을 지원받고 비즈니스를 자동화하는 실무 역량을 기릅니다.',
  },
  {
    id: 'synergy',
    section: 'scenarios',
    title: 'Integrated Package Synergy',
    headline: '분절된 솔루션이 아닌,\n단일 통합 패키지',
    body: '비용 절감 · 효율 향상 · 보안 강화를 동시에',
    type: 'before-after',
    transition: 'morph',
    effects: ['particle-convergence', 'kpi-counter', 'core-glow'],
    keywords: ['비용 절감', '효율 향상', '보안 강화'],
    data: {
      scattered: ['VDI', 'GPU', 'AI 플랫폼', 'LMS', 'CBT', '보안'],
      effects3: [
        { label: '비용', word: '절감' },
        { label: '효율', word: '향상' },
        { label: '보안', word: '강화' },
      ],
    },
    speakerNote: '이처럼 분절된 솔루션이 아닌 단일 통합 패키지로 시너지를 극대화할 수 있습니다. 이에 따라 대학의 AI 인프라 비용은 절감되고 효율과 보안은 크게 향상될 것입니다.',
  },

  // ───────────────────────── 7. PLATFORM ─────────────────────────
  {
    id: 'platform-intro',
    section: 'platform',
    title: 'All-in-One Education Platform',
    headline: '강의 · 학습 · 과제 · 실습 · 평가,\n하나의 플랫폼에서',
    body: 'AI 시대의 수업과 평가는 달라져야 한다',
    type: 'orbit-platform',
    transition: 'zoom',
    effects: ['orbit-menu', 'circle-drawing', 'kinetic-typography'],
    keywords: ['강의', '학습', '과제', '실습', '평가'],
    data: {
      orbit: ['강의', '학습', '과제', '실습', '평가'],
      audience: ['교수', '학생'],
    },
    speakerNote: 'AI 시대의 수업, 강의와 시험 평가는 달라져야 합니다. 강의, 학습, 과제, 실습, 평가를 하나의 플랫폼에서 운영하여 교수와 학생 모두의 학습 효율을 극대화할 수 있는 All-in-One 교육 플랫폼에 대해 말씀드리겠습니다.',
  },
  {
    id: 'cas',
    section: 'platform',
    title: 'CAS Platform',
    headline: '수업별 온라인 그룹에서\n강의부터 평가까지',
    body: 'CAS — Class As a Service',
    type: 'ui-modules',
    transition: 'push',
    effects: ['ui-hotspot', 'module-reveal', 'magnetic-card'],
    keywords: ['강의', '과제 제출', '실습일지', '평가'],
    data: {
      modules: [
        { name: '강의', desc: '수업별 온라인 그룹' },
        { name: '학습', desc: '자료 · 진도 관리' },
        { name: '과제 제출', desc: '제출 · 피드백' },
        { name: '실습일지', desc: '실습 기록 관리' },
        { name: '평가', desc: '성과 측정' },
      ],
    },
    speakerNote: '틸론의 CAS는 수업별로 별도의 온라인 그룹을 만들어 강의, 학습, 과제 제출, 실습일지 작성, 평가 등을 하나의 플랫폼에서 관리할 수 있습니다.',
  },
  {
    id: 'cbt',
    section: 'platform',
    title: 'DaaS 기반 CBT',
    headline: '부정행위 차단 · 자동 채점 ·\nAI 문제 생성 · 성과 분석',
    body: '차세대 평가 플랫폼',
    type: 'cbt-secure',
    transition: 'wipe',
    effects: ['secure-exam', 'process-lock', 'allow-block-toggle'],
    keywords: ['부정행위 차단', '자동 채점', 'AI 문제 생성', '학습성과 분석'],
    data: {
      videos: [
        { src: 'cbt-demo-1', label: '동영상 사례형 문제 응시 화면' },
        { src: 'cbt-demo-2', label: 'CBT 문제풀이 · 메모 작성' },
      ],
      allowed: ['시험 화면', '허용 프로그램', '문제별 메모'],
      blocked: ['브라우저', '메신저', '미허용 프로그램'],
      control: '로컬 PC + 가상 PC 프로세스 동시 통제',
    },
    speakerNote: 'DaaS 기반 CBT는 부정행위 차단, 자동 채점, AI 문제 생성, 학습성과 분석을 통합한 차세대 평가 플랫폼입니다. 실제 학생 응시 화면에서는 동영상을 활용한 사례형 문제까지 자유롭게 출제됩니다. 문제별 개별 메모 작성이 가능하고 허용된 프로그램을 시험에 활용할 수 있습니다. 학생은 가상 PC에 접속하여 CBT 시험에 응시하며, CBT 실행 시 로컬 PC와 가상 PC에서 실행되는 프로세스를 동시에 통제합니다. 허용되지 않은 프로그램, 브라우저, 메신저 등은 실행 차단됩니다.',
  },

  // ───────────────────────── 8. CASES ─────────────────────────
  {
    id: 'cases-intro',
    section: 'cases',
    title: 'University Cases',
    headline: '국내 대학들은 이미\n전환을 시작했다',
    body: '',
    type: 'case-map',
    transition: 'zoom',
    effects: ['map-nodes', 'network-drawing', 'mouse-parallax'],
    keywords: ['서강대', '제주대', '동아대', '백석대', '상명대', '고려사이버대'],
    data: {
      nodes: [
        { name: '서강대학교', x: 46, y: 30 },
        { name: '상명대학교', x: 56, y: 24 },
        { name: '고려사이버대', x: 62, y: 34 },
        { name: '백석대학교', x: 48, y: 48 },
        { name: '동아대학교', x: 74, y: 72 },
        { name: '제주대학교', x: 38, y: 90 },
      ],
    },
    speakerNote: '이제부터는 국내 대학의 도입 성공사례에 대해서 말씀드리겠습니다.',
  },
  {
    id: 'sogang-case',
    section: 'cases',
    title: '서강대학교',
    headline: '국내 최초, SW중심대학\n2회 연속 선정',
    body: '가상PC 기반 교육 인프라의 대표 사례',
    type: 'case-timeline',
    transition: 'push',
    effects: ['timeline', 'case-card', 'gpu-addon'],
    keywords: ['SW중심대학', '가상PC', 'GPU 가상화', '산학협력'],
    data: {
      univ: 'Sogang University',
      timeline: [
        { year: '2014', label: '제1회 SW중심대학 선정', desc: '컴퓨터공학과 전학생 가상PC 제공 — 차별 없는 학습환경' },
        { year: '2024', label: '국내 최초 2회 연속 선정', desc: 'GPU 가상화 접목, 산학협력 모델 강화 · 현장 중심 교육과정 확대' },
      ],
    },
    speakerNote: '2014년 제1회 SW중심대학에 선정된 서강대학교는 컴퓨터공학과 전학생 대상 가상PC를 제공해 차별 없는 학습환경을 구현했습니다. 10년이 지난 2024년에는 국내 최초로 SW중심대학 2회 연속 선정이 되었습니다. 가상PC에 GPU 가상화를 접목하여 산학협력 모델을 강화하고 현장 중심 교육과정을 확대해가고 있습니다.',
  },
  {
    id: 'jeju-case',
    section: 'cases',
    title: '제주대학교',
    headline: '전교생 3A 학습환경,\n국립대 표준 모델',
    body: 'Anyone · Anytime · Anywhere',
    type: 'case-stats',
    transition: 'push',
    effects: ['number-counter', 'orbit-3a', 'sw-streaming'],
    keywords: ['5,381대 VDI', '전교생 1만 명', '3A'],
    data: {
      univ: 'Jeju National University',
      stats: [
        { value: 5381, label: 'VDI 도입', suffix: '대' },
        { value: 10000, label: '전교생 확장 목표', suffix: '명', approx: true },
      ],
      threeA: ['Anyone', 'Anytime', 'Anywhere'],
      points: ['고가 SW 중앙집중 관리', 'GPU 자원 배분', '저사양 단말에서 Photoshop · SPSS 실습'],
    },
    speakerNote: '제주대학교는 RISE 사업으로 5,381대 VDI를 도입한 국내 국립대의 표준 모델입니다. 약 1만 명에 달하는 전교생에게 VDI 배포를 목표로 하고 있으며, Anyone, Anytime, Anywhere, 즉 3A 학습환경을 구현했습니다. 고가 SW를 학과별로 따로 관리할 필요 없이 가상PC로 중앙집중 관리하고, GPU 자원 배분으로 저사양 단말기에서도 Photoshop, SPSS 같은 통계 SW 실습을 원활하게 수행하고 있습니다.',
  },
  {
    id: 'donga-case',
    section: 'cases',
    title: '동아대학교',
    headline: '원격 실습과 ISMS-P 인증,\n동시에 잡다',
    body: '부산지역 12개 대학 원격교육 네트워크',
    type: 'case-security',
    transition: 'push',
    effects: ['regional-network', 'compliance-grid', 'shield'],
    keywords: ['12개 대학', 'ISMS-P', '가상GPU'],
    data: {
      univ: 'Dong-A University',
      network: '부산지역 12개 대학 원격교육',
      compliance: ['접근통제', '정보시스템 보안', '운영관리'],
      benefit: '인증 비용과 시간 동시 절감',
    },
    speakerNote: '동아대학교는 부산지역 12개 대학과 함께하는 원격교육 지원을 위해 가상PC를 도입했습니다. 가상GPU 자원으로 설계, AI 모델링 등 다양한 실습을 원격 수업 인프라로 활용하고 있습니다. 특히 ISMS-P 인증 획득을 목표로 데스크톱 가상화를 도입한 사례입니다. VDI는 접근통제, 정보시스템 보안, 운영관리를 자연스럽게 충족시켜 인증 비용과 시간을 동시에 절감합니다.',
  },
  {
    id: 'baekseok-case',
    section: 'cases',
    title: '백석대학교',
    headline: '노후 PC로도\nUnreal · Unity를 돌린다',
    body: '천안 제조산업 특화단지 — 산업연계 실증 교육',
    type: 'case-morph',
    transition: 'push',
    effects: ['oldpc-morph', 'sw-icons', 'resource-streaming'],
    keywords: ['노후 PC', 'Unreal', 'Unity', '설계 SW'],
    data: {
      univ: 'Baekseok University',
      before: '노후 PC 실습실',
      after: '게임 · 설계 SW 실행 환경',
      sw: ['Unreal', 'Unity', '설계 SW'],
      context: '천안 제조산업 특화단지 · 산업연계 실증 교육',
    },
    speakerNote: '천안의 제조산업 특화단지에 위치한 백석대학교는 산업연계 실증 교육의 필요성이 높아졌고, 틸론 솔루션을 도입하여 노후 PC를 활용한 게임 및 설계 소프트웨어, Unreal, Unity 등을 운영하고 있습니다.',
  },
  {
    id: 'sangmyung-case',
    section: 'cases',
    title: '상명대학교',
    headline: '검증된 안정성 위에,\n통합 개발환경을 얹다',
    body: 'Windows / Linux 개발환경 실시간 제공',
    type: 'case-validation',
    transition: 'push',
    effects: ['validation-flow', 'os-toggle', 'workspace-cards'],
    keywords: ['운영 안정성 검증', 'Windows', 'Linux'],
    data: {
      univ: 'Sangmyung University',
      flow: [
        { name: '서강대학교', desc: '대규모 VDI 운영 안정성 검증' },
        { name: '상명대학교', desc: '검증 후 도입 결정' },
      ],
      os: ['Windows', 'Linux'],
      point: '학생별 최적화된 개발환경 실시간 제공',
    },
    speakerNote: '상명대학교는 서강대학교에서 실제 활용 중인 대규모 VDI 환경의 기술 및 운영 안정성을 검증한 후 도입을 결정한 사례입니다. 학생들에게 Windows 또는 Linux 기반의 최적화된 통합 개발 환경을 실시간 제공하고 있습니다.',
  },
  {
    id: 'cuk-case',
    section: 'cases',
    title: '고려사이버대학교',
    headline: '입시경쟁률\n+21.5%',
    body: 'Virtual Lab — 전기전자회로계측 온라인 실습',
    type: 'case-kpi',
    transition: 'push',
    effects: ['data-counter', 'circuit-lines', 'impact-pulse'],
    keywords: ['Virtual Lab', '21.5%'],
    data: {
      univ: 'The Cyber University of Korea',
      kpi: { value: 21.5, suffix: '%', label: '입시경쟁률 상승' },
      lab: ['전기전자회로계측 SW', '온라인 실습', 'Virtual Lab'],
    },
    speakerNote: '고려사이버대는 전기전자회로계측 SW 등을 가상으로 실습할 수 있는 Virtual Lab으로 입시경쟁률을 21.5% 상승시켰습니다.',
  },

  // ───────────────────────── 9. IMPACT & CLOSING ─────────────────────────
  {
    id: 'impact',
    section: 'impact',
    title: 'Total Impact',
    headline: '숫자가 증명하는 변화',
    body: '대학의 글로벌 경쟁력 향상으로 이어진다',
    type: 'kpi',
    transition: 'zoom',
    effects: ['kpi-counter', 'chart-drawing', 'particle-accent', 'impact-ring'],
    keywords: ['9배', '42%', '보안 강화'],
    data: {
      kpis: [
        { value: 9, suffix: '배', label: 'GPU 활용률', decimals: 0 },
        { value: 42, suffix: '%', label: '학습환경 향상', decimals: 0 },
        { value: null, word: '강화', label: '행정 효율 · 데이터 보안' },
      ],
    },
    speakerNote: '오늘 소개해 드린 틸론의 솔루션은 GPU 활용률 9배, 학습환경 42% 향상, 행정 효율 및 데이터 보안을 강화하여 대학의 글로벌 경쟁력을 향상시켜 드립니다.',
  },
  {
    id: 'closing',
    section: 'impact',
    title: 'Closing',
    headline: 'Build AI Native Campus',
    body: '전 세계 AI 네이티브들과 경쟁할 수 있는 대학의 AI 교육 생태계',
    type: 'closing',
    transition: 'morph',
    effects: ['particle-convergence', 'global-network', 'webgl-glow', 'generative-background'],
    keywords: ['AI Native Campus', 'Future Learning Infrastructure'],
    data: {
      cta: ['Build AI Native Campus', 'Create the Future Learning Infrastructure'],
      thanks: '감사합니다 · Q&A',
    },
    speakerNote: '전 세계 AI 네이티브들과 경쟁할 수 있는 혁신적인 대학의 AI 교육 생태계를 위한 교육 인프라를 만들어 가겠습니다.',
  },
];

export function sectionOf(scene) {
  return SECTIONS.find((s) => s.id === scene.section);
}
